apiVersion: v1
kind: Service
metadata:
  name: app-user
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: app-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-user
  labels:
    app: app-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-user
  template:
    metadata:
      labels:
        app: app-user
    spec:
      containers:
      - name: app-user
        image: localhost:5000/user-app:1.1
        ports:
        - containerPort: 80